VERSION_NAME=0.0.2-SNAPSHOT
GROUP=com.quonfig
POM_ARTIFACT_ID=sdk-java

POM_NAME=Quonfig Java SDK
POM_DESCRIPTION=Java SDK for Quonfig - feature flags and configuration as files in git.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/quonfig/sdk-java

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/quonfig/sdk-java
POM_SCM_CONNECTION=scm:git:git://github.com/quonfig/sdk-java.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/quonfig/sdk-java.git

POM_DEVELOPER_ID=quonfig
POM_DEVELOPER_NAME=Quonfig
POM_DEVELOPER_URL=https://quonfig.com/
